// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgsBl-0TOFKR03WX0d-Bb12kH_w-2bGuc',
    appId: '1:599271562021:web:87710343c43245b75818cc',
    messagingSenderId: '599271562021',
    projectId: 'testprojectdata-e56c1',
    authDomain: 'testprojectdata-e56c1.firebaseapp.com',
    storageBucket: 'testprojectdata-e56c1.appspot.com',
    measurementId: 'G-9GVZZECRFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9FddWUFVHxOsXkGoCkL--to6Wrom043w',
    appId: '1:599271562021:android:c6ba7eaaefdc13e45818cc',
    messagingSenderId: '599271562021',
    projectId: 'testprojectdata-e56c1',
    storageBucket: 'testprojectdata-e56c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLrXdUtowJlMvYuMPsR8G76AnBaXlULbw',
    appId: '1:599271562021:ios:c100c4a81007dc2c5818cc',
    messagingSenderId: '599271562021',
    projectId: 'testprojectdata-e56c1',
    storageBucket: 'testprojectdata-e56c1.appspot.com',
    androidClientId: '599271562021-t4sbvk2aeli7oe24q55h9o7t5mddogps.apps.googleusercontent.com',
    iosClientId: '599271562021-okbgg1sn346k32vmq3ej9o8pohhuslln.apps.googleusercontent.com',
    iosBundleId: 'com.example.testappSocialmedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLrXdUtowJlMvYuMPsR8G76AnBaXlULbw',
    appId: '1:599271562021:ios:0abe5b02ceae29455818cc',
    messagingSenderId: '599271562021',
    projectId: 'testprojectdata-e56c1',
    storageBucket: 'testprojectdata-e56c1.appspot.com',
    androidClientId: '599271562021-t4sbvk2aeli7oe24q55h9o7t5mddogps.apps.googleusercontent.com',
    iosClientId: '599271562021-v2ajnb87mo7323nh7m5kmmtrbhljn9rt.apps.googleusercontent.com',
    iosBundleId: 'com.example.testappSocialmedia.RunnerTests',
  );
}
